### PR TITLE
Creating hamburger menu for dashboard

### PR DESCRIPTION
**Pull request by riyasingh1004**
Fixes#133

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by Vipinsoni38** [comment]
@riyasingh1004 I think the menu is already a hamburger menu, So what are you trying to change?

**Comment by riyasingh1004** [comment]
No a hamburger menu is a dotted overflow menu and it is not present in the dashboard.

**Comment by Vipinsoni38** [comment]
Cool! well you can add App Settings, Help and Feedback in it

don't add log out because its already there in navigation drawer

**Comment by riyasingh1004** [comment]
Ya I think that's a good idea. Thank you

**Comment by miPlodder** [comment]
menu is not tied to Fragment and do keep the PR Title consistent. 
Anyways, not needed. 
@therajanmaurya You can close it if you think this use-case is not required.

**Comment by therajanmaurya** [comment]
Like currently we don't have any feature list to use this UI. So closing it.

**Pull request closed without merging**
