### PR TITLE
Bug: Nav bar overflow issue solved for new mobile screen sizes

### PR DESCRIPTION
**Pull request by varsvat**
#Fixes #Issue_number

The profile avatar icon is cut because of overflow of nav drawer in new mobile models as shown below:

profileIconCut

I have solved this issue and now it works fine as shown below: 

profileIconCutIssue_solved

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything.

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Review by EGOR-IND — APPROVED** [review]
I don't know why you repositioned so many lines just to make  'fitsSystemWindows' false. it makes checking changes a bit confusing but overall nice work:).

**Comment by varsvat** [comment]
I actually did not purposely did this, I just formatted the code which repositioned the lines :sweat_smile: . Thank you @EGOR-IND for letting me know this .... makes sense . I'll keep this in mind now onwards .

**Comment by varsvat** [comment]
@therajanmaurya @edcable @jawidMuhammadi Please review this when you have time.

**Review by jawidMuhammadi — APPROVED** [review]
LGTM!

**Pull request closed without merging**
