### PR TITLE
resolve the bad CreateCustomerActivity exit pattern

### PR DESCRIPTION
**Pull request by EGOR-IND**
Fixes [FINCN-277](https://issues.apache.org/jira/browse/FINCN-277)

https://user-images.githubusercontent.com/56648862/111373087-813cfd00-86c1-11eb-8953-92c641674477.mp4

Made the customer create and edit activity's exit experience better

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything.

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Review by varsvat — APPROVED** [review]
Actually I did not thought of placing a dialog box here, It gives a better UX, great work @EGOR-IND !! I'll add this feature in my PR and also for other stepLayouts.

**Review by PatelVatsalB21 — APPROVED** [review]
Looks very good needs to be implemented in #144

**Comment by varsvat** [comment]
> Looks very good needs to be implemented in #144

Implemented in #144 .

**Comment by EGOR-IND** [comment]
Closing this PR, all my changes will be available in #144.

**Pull request closed without merging**
