### PR TITLE
Feat: Offline first approach using couchbase lite

### PR DESCRIPTION
**Pull request by jawidMuhammadi**
Fixes #Issue_number

Please Add Screenshots If any UI changes.

***Couchbase Server:***

rsz_screenshot_from_2020-08-22_22-12-56

***Sync Gateway:***

rsz_screenshot_from_2020-08-25_18-30-11

Please Add Summary of what changes you have made and if possible provide links.(Optional)

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything.

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by EGOR-IND** [comment]
Hey @jawidMuhammadi, can I ask that after integrating couchbase do we need to select online or offline mode for doing things like in CustomerListFragment because it's an offline first approach. Actually I was reading your gist while understanding this PR, so a little doubt came to my mind:).

**Comment by jawidMuhammadi** [comment]
> Hey @jawidMuhammadi, can I ask that after integrating couchbase do we need to select online or offline mode for doing things like in CustomerListFragment because it's an offline first approach. Actually I was reading your gist while understanding this PR, so a little doubt came to my mind:).

**Comment by jawidMuhammadi** [comment]
@EGOR-IND Nope, I am not sure if we need a switch to offline or online mode. We are using Couchbase Sync Gateway, so it will cache the data if there isn't internet then sync all cached data automatically when the device connects to the internet.

**Comment by EGOR-IND** [comment]
> @EGOR-IND Nope, I am not sure if we need a switch to offline or online mode. We are using Couchbase Sync Gateway, so it will cache the data if there isn't internet then sync all cached data automatically when the device connects to the internet.

Yeah, that's what I was thinking, we're going to use sync gateway, okay I'll try this offline mode on a dummy app, thanks for resolving this doubt.

**Pull request merged**
