### PR TITLE
Fix-258: FAB in Manage roles removed

### PR DESCRIPTION
**Pull request by PatelVatsalB21**
Fixes FINCN-258
As we can't create new roles it unnecessary to keep that fab that doesn't responds.

**Error**

https://user-images.githubusercontent.com/70195106/111077626-adb51580-8517-11eb-82bb-27735d3b98e0.mp4

**Solution**

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything.

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by EGOR-IND** [comment]
@PatelVatsalB21 you just created an issue for this and I commented on that please check that comment. Don't rush to make a PR first think about your issue my friend sometimes we think the issue is correct but it doesn't mean it's always correct. I don't mean to offend you, just want you to be more aware:).

**Comment by PatelVatsalB21** [comment]
> @PatelVatsalB21 you just created an issue for this and I commented on that please check that comment. Don't rush to make a PR first think about your issue my friend sometimes we think the issue is correct but it doesn't mean it's always correct. I don't mean to offend you, just want you to be more aware:).

Ok I got it and i will take care of it :) but simple issues take less time so i made pr instantly.

**Comment by PatelVatsalB21** [comment]
@EGOR-IND surely i wil take care of it.

**Comment by EGOR-IND** [comment]
I didn't mean that, there is no problem in creating a PR fast, I'm just
saying that issue you raised had a little flaw because if you see that fab
is for creating role, i think in future there will be some work done on
this therefore the fab is not unnecessary😊. I'm just trying to help after
all we are working in team.

**Pull request closed without merging**
