### PR TITLE
Feat: Add support for viewing, creating, updating and deleting Roles

### PR DESCRIPTION
**Pull request by jawidMuhammadi**
Fixes #FINCN-44

In this PR following functionalities added for Role/Permission:

1. Displaying Role details
2. Creating a new Role
3. Updating a Role
4. Deleting a Role

**1.  Creating a new Role**

create

**2.  Editing, Updating and Deleting Roles**

edit_delete

Please Add Screenshots If any UI changes.

Screenshot_1584649754
Screenshot_1584649749
Screenshot_1584649744
Screenshot_1584649737
Screenshot_1584649726
Screenshot_1584649707

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything.

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by jawidMuhammadi** [comment]
@therajanmaurya Please review the PR. Thanks

**Comment by prajwal27** [comment]
@jawidMuhammadi could you share the link of the API documentation. Also, how did you verify without actual network response.

**Comment by jawidMuhammadi** [comment]
@prajwal27 Yeah sure, Go to this [link](https://cwiki.apache.org/confluence/display/FINERACT/Fineract+CN) you will find all the information about Fineract and it's documentation. The the backend is not hosted in any server, so we have to play with simulated API calls and Mock data.

**Comment by varsvat** [comment]
@jawidMuhammadi why has this PR been closed and not merged?

**Pull request closed without merging**
